### ISSUE TITLE
Add new instructors as Carpentry@UiO community members

### ISSUE THREAD

**Issue by desireetreichler** [uio-carpentry/organisational#103]
Consequence of updated mentoring document: https://github.com/uio-carpentry/organisational/pull/102#issue-1285688247
I don't have the overview over current (new) instructors... we may also have to clarify whose task this is? The library representatives? -> add other assignees if someone else has the overview

**Comment by arockenberger** [comment]
I agree; this is a task we at the library will take on. I have added @sofgilbert to this Issue and we will fix it.

At this point in time, we might go for an instructor/helper status survey, as we did in 2019.
