### ISSUE TITLE
Add missing members to the HackMD team

### ISSUE THREAD

**Issue by desireetreichler** [uio-carpentry/organisational#104]
Two board members are missing and thus can't edit our board meeting agendas/minutes. They should be added as admins using their github account email addresses (which I don't have), as that's what is used to log in to the HackMD team.

I already updated the onboarding document with this task for the next board transition: https://github.com/uio-carpentry/organisational/blob/master/board/on-offboarding_board.md#checklist-for-onboarding-incoming-and-offboarding-outgoing-board-members

**Comment by arockenberger** [comment]
I have added @Me6me82 and sent an invite link to @sofgilbert and @CSGeer. I have also removed past board members.
