### ISSUE TITLE
Getting in touch with CodeRefinery 

### ISSUE THREAD

**Issue by bianchini88** [uio-carpentry/organisational#113]
We need to find out whether we want to provide the "Bring your own classroom" for the [CR WS in September](https://coderefinery.github.io/2024-09-10-workshop/) (10-12 and 17-19, 9:00-13:00 CEST). 

If we want to go ahead with this, we should probably:  
- [X] Find people to host the sessions (not necessarily experts)
- [X] Book a room
- [X] Announce the event

~~I am a bit unsure whether we actually need to communicate with the organisation or not... it probably will not hurt if we get far enough in the process.~~

~~If we feel the time is too tight, we could probably just~~
- ~~[ ] Announce the event~~

~~and engage earlier next time. ~~

**Comment by mariapie** [comment]
Yep! I have looked for room and the situation is not the best. I plant to send the email tomorrow for ask for people and if there are enough people that we will try to solve the room problem. Meanwhile My has prepare the online workshop webpage for Coderefinery and i think that is already up and running :)

**Comment by bianchini88** [comment]
> Yep! I have looked for room and the situation is not the best. I plant to send the email tomorrow for ask for people and if there are enough people that we will try to solve the room problem. Meanwhile My has prepare the online workshop webpage for Coderefinery and i think that is already up and running :)

Fantastic!

**Comment by bianchini88** [comment]
@mariapie Was the event announced?
