### ISSUE TITLE
Checklists: mailinglist discuss @ swcarpentry

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#16]
Regarding updating of checklists in workshop_operations (https://github.com/uio-carpentry/organisational/blob/master/workshop_operations/checklists.md)

It says that all people who have attended and those on the organisers list are to be signed up for the discuss list.
"* discuss @ swcarpentry dot uio dot no --> all people that have attended workshops + those on the organisers list"

As far as I can see, this list is not actively used.

I propose we delete this list.

**Comment by lexnederbragt** [comment]
I agree, we never got that list to work as intended.

**Comment by arockenberger** [comment]
Ok, I will delete the info in the checklist and suggest someone with sympa privileges deletes the list (I don't have those).

**Comment by arockenberger** [comment]
Mailing list deleted by IT as of 2019-12-19
