### ISSUE TITLE
Checklists: Pre-workshop questionnaire

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#17]
Regarding updating of checklists in workshop_operations (https://github.com/uio-carpentry/organisational/blob/master/workshop_operations/checklists.md)

It says in the part about instructor duties:
"* obtain and send pre-workshop questionnaire to attendants"

Do we use pre-workshop questionnaires for our un-official Carpentries workshops?

If not:

a) Should we create a pre-workshop questionnaire?
OR
b) Delete this item.

**Comment by lexnederbragt** [comment]
a) if possible.

**Comment by arockenberger** [comment]
@naoe-tatara confirmed that we can (and should) use the Carpentries pre-workshop surveys also for self-organized, non-standard workshops (called "Mix & Match") as long as they are based on Carpentries lessons. I will thus delete this Issue.
