### ISSUE TITLE
Checklists: Registration handling

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#18]
Regarding updating of checklists in workshop_operations (https://github.com/uio-carpentry/organisational/blob/master/workshop_operations/checklists.md)

In the part about the instructors' responsibilities it says:

"*  download the registration information from `nettskjema.uio.no`, add one column for each workshop day and add an `x` for those participants that were present; send this excel sheet to the 'carpadmin at swcarpentry.uio.no' list"

I advise AGAINST sending registration information to a mailinglist. We can either store the registration info in a UiO G-Suite folder or send the registration info with an official UiO email address (not @ gmail etc.!) to the local coordinator for storing.

I need your input on this!

**Comment by lexnederbragt** [comment]
I agree that we should follow UiO 'lagringsguiden' etc. As long as UiO email is used, I think this is fine. But that means the _sender_ needs to use uio mail. I am uncertain if all our instructors are comfortable using a UiO-enabled cloud service, especially without training. It's fun juggling two Google accounts...

**Comment by arockenberger** [comment]
**Update**: In the future, Carpentry@UiO will use Pindena for handling registration, waiting lists, creating certificates of participation, and workshop-surveys. The system lends itself better to automated tasks and reduces the number of steps that have to be taken in order to coordinate workshops.
Access to Pindena will be restricted to the Carpentry@UiO coordinator and the regional Coordinator, with a backup person at the University Library. Thus, instructors don't have to hassle with setting up any additional websites or forms and we can streamline orders for catering and communication, too.
I will write up a How-To guide for Pindena for the coordinator(s) which will be shared via UiO G-Suite.
Changes effective for workshops held after 1st January 2020.
