### ISSUE TITLE
Checklists: Send workshop info to Carpentries

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#19]
Regarding updating of checklists in workshop_operations (https://github.com/uio-carpentry/organisational/blob/master/workshop_operations/checklists.md)

In the part about instructors' responsibilities it says:

"for official The Carpentries workshops, send Software Carpentry or Data Carpentry admin the number of attendants for both days"

I think we should add a link here, but I cannot find the contact information anywhere on the Carpentries website.

Please help!

**Comment by lexnederbragt** [comment]
I am pretty sure this is team@carpentries.org.

**Comment by arockenberger** [comment]
Added this to the updated checklist. Closing Issue
