### ISSUE TITLE
Checklists: Post-workshop assessment

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#20]
Regarding updating of checklists in workshop_operations (https://github.com/uio-carpentry/organisational/blob/master/workshop_operations/checklists.md)

The checklist says:

"* obtain the post-workshop assessment form link from the workshop's uio-carpentry.github.io pages, or from SWC/DC admin"

I do not understand this sentence. Please help to clarify!

**Comment by lexnederbragt** [comment]
This should be 'Post-workshop Survey link.' Example: https://uio-carpentry.github.io/2018-06-07-Oslo/. These links are autogenerated when you set up the workshop website.

**Comment by arockenberger** [comment]
@naoe-tatara confirmed that we can (and should) use the Carpentries post-workshop survey even for self-organized, non-standard workshops ("Mix & Match") as long as they are based on the Carpentries lessons. I will close this Issue now. There is still the question of a Carpentry@UiO evaluation survey, but this is addressed in #33
