### ISSUE TITLE
Workshop Operations: Therapy-folder

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#24]
(https://github.com/uio-carpentry/organisational/blob/master/therapy/160429_meetingMinutes.md)

This looks like its meeting minutes; I suggest this to be moved to the meetings-folder instead;

Is there any activity around "Data Therapy" or can we consider this to be put aside?

**Comment by karinlag** [comment]
Data therapy was more or less a precursor to the Study Group. Think it can be closed.

**Comment by arockenberger** [comment]
Ok; will move the minutes into the meetings-folder

**Comment by arockenberger** [comment]
Creating a pull-request from branch arockenberger-patch-1
