### ISSUE TITLE
Workshop Operations: Testimonials

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#25]
(https://github.com/uio-carpentry/organisational/blob/master/testimonials.md)

What are we using these for?

Are we collecting more / different testimonials in this file?

**Comment by lexnederbragt** [comment]
To show others how useful Carpentry@UiO is! We have no good routines to collect more, but the idea is to use the post-workshop feedback

**Comment by arockenberger** [comment]
Ok! I suggest to make a folder called "Promotional" then and add the Logo folder and the testimonials file in there.
