### ISSUE TITLE
Comments on new onboarding page

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/organisational#40]
I was too late to comment on the PR so here it goes :-) Comments to https://github.com/uio-carpentry/organisational/blob/master/workshop_operations/onboarding-checklist.md

* "I want to teach a workshop!" should maybe say that we prefer workshops are taught by at least one certified Carpentries instructor, but that people can contact us in case they don't meet that requirement but would still like to organise something?
* After 'I want to teach a workshop!' maybe add 'What lesson can I teach? and mention lessons from http://software-carpentry.org/lessons/, http://datacarpentry.org/lessons/ but that we also are open for other lessons by asking us
* "Submit your workshop to the Carpentries database by following the instructions on this website https://amy.carpentries.org/forms/self-organised/" --> it seems we leave this up to each instructor, but would it be a good idea carpadmin either checks that this happens for each workshop or does it for our instructors? It would be a pity if this step was forgotten...
* "Do a short security briefing in the beginning of the workshop" not sure what this is...?

**Comment by arockenberger** [comment]
Thanks for your comments! 
I will incorporate them / explicate them on the weekend before the first onboarding session.

**Comment by arockenberger** [comment]
+ Item 1: added line (line 10)
+ Item 2: added lines (line 13-16)
+ Item 3: added sentence (line 32)
+ Item 4: short security briefing: I tell people to inform the participants that there is no scheduled fire drill, so if they hear the alarm, they ought to leave the building. I also ask them to point out the nearest exit and how to leave the building in case of fire or another emergency. It's actually mandatory to do this for all events at UiO, but almost no one knows or does it. 

Created Pull Request, you may merge it!
