### ISSUE TITLE
Add file CONTRIBUTING.md

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#48]
We need to put down some lines about how to contribute to this repo.

If someone feels inclined to – start a document!

It should reflect good project management practices like creating Issues, making changes on a new branch, creating a Pull Request, asking someone for a review, Merging Pull Requests etc.

Should include a link to our Code of Conduct, too.

**Comment by lexnederbragt** [comment]
Here is a good example we could use as starting point: https://github.com/carpentries/instructor-training/blob/gh-pages/CONTRIBUTING.md

**Comment by arockenberger** [comment]
This looks really good, yes. Thanks, Lex!
If someone (not me) wants to go ahead and start adapting the file for our purposes, go ahead!

**Comment by lexnederbragt** [comment]
I am giving this a go
