### ISSUE TITLE
The new board will go through the governance documents and will update it accordingly

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#53]
Action Point, see [minutes](https://github.com/uio-carpentry/organisational/blob/master/meetings/200325-board-meeting.md#aob)

**Comment by naoe-tatara** [comment]
I went through, left some comments on the existing issues there, made one new issue, and sent PRs to fix one issue. (Not sure if we need to report something like this here or just work on governance repo). When are we going to move this to "in progress" in the project page?

**Comment by arockenberger** [comment]
Moved it! You can do this by clicking on the Projects tab in the menu on the right side of this page, there is a fold-out button where you can change the status.
But I see that this Issue should probably have been put into governance, not in organisational…
Thanks for the Issues there and the quick fix of the mailto-links!

**Comment by arockenberger** [comment]
I think this is sufficiently delt with. The work on the governance documents continues, but should be tracked with Issues in its own repository.
