### ISSUE TITLE
Doodle for setting up the next Board meeting

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#54]
Action point, see [meeting minutes](https://github.com/uio-carpentry/organisational/blob/master/meetings/200325-board-meeting.md#aob)

**Comment by arockenberger** [comment]
Looks like Doodle is a paid service now…
Is anyone here aware of a good (and gratis) alternative we could use?

**Comment by annesbe** [comment]
https://framadate.org might do the trick, though I haven't tried it.

**Comment by arockenberger** [comment]
I'll give it a try! Thx!

**Comment by lexnederbragt** [comment]
I think you can ignore the 'sign up for free trial' and click on the 'Create a Doodle' button at the top-right...

**Comment by lexnederbragt** [comment]
Another alternative that I like is http://whenisgood.net.

**Comment by arockenberger** [comment]
Decided to try whenisgood, sent out invitations to board mailing list on 2020-04-15
