### ISSUE TITLE
New board will organize appointment of chair, vice-chair and communication officer

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#55]
See [meeting minutes](https://github.com/uio-carpentry/organisational/blob/master/meetings/200325-board-meeting.md#aob)

**Comment by naoe-tatara** [comment]
If no one is interested in, I can be a communication officer.

**Comment by lexnederbragt** [comment]
Email soliciting candidates sent to board.

**Comment by Teebusch** [comment]
Roles were approved in the meeting yesterday. Unfortunately I was busy setting up my note taking and missed who was confirmed as vice chair. Can someone update the notes please? After that, the issue can be closed, I suppose.

https://github.com/uio-carpentry/organisational/blob/master/meetings/200506-board-meeting.md

**Comment by lexnederbragt** [comment]
Done!
