### ISSUE TITLE
Add git-free solutions to CONTRIBUTING.md

### ISSUE THREAD

**Issue by lexnederbragt** [uio-carpentry/organisational#57]
CONTRIBUTING.md focuses on git only, and a lot can be done without having to close repos and go through command-line git, i.e., through GitHub only. Could the document describe both workflows?

**Comment by arockenberger** [comment]
Hm, I think it shows several ways of contributing, incl. via email (no knowledge or setup of git or GitHub necessary), already.
But I agree that we could discuss if there are other ways we could think of contributions that are technology-independent!

**Comment by lexnederbragt** [comment]
I meant to put in a PR for this but ended up pushing to master, sorry. But here is what I had in mind: https://github.com/uio-carpentry/organisational/commit/8b4ebb6090a3900c5fac27ad93a93a7799cff7fb

**Comment by arockenberger** [comment]
Alright then! Closing the Issue :)
