### ISSUE TITLE
Carpentry@UiO Instructor Training Spots - Criteria

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#60]
https://github.com/uio-carpentry/organisational/blob/master/meetings/200506-board-meeting.md#instructor-training-spots-for-next-year

combine the advantages of using a rating system together with a sponsor system, thus trying to avoid the disadvantages of both systems.

@action Annika will formulate a strategy that the Board will use to decide who gets offered a spot for 2020-2021.

**Comment by arockenberger** [comment]
I will condense the deliberations from the GoogleDoc into a document to be reviewed by the Board. The document will be made public in this repo: transparency rulez!

**Comment by arockenberger** [comment]
I have created a document for the criteria https://github.com/uio-carpentry/organisational/blob/master/board/instructor-spots.md – please read it carefully and review (responding to this Issue or by making pull-requests (but don't merge them yourself!).
@Teebusch @lexnederbragt @vivigirardin @naoe-tatara @annesbe

**Comment by lexnederbragt** [comment]
Thanks, @arockenberger, great text! I have a minor comment:

> and/or contributes to Carpentry@UiO’s GitHub repositories

How realistic is this? Has this ever happened?

**Comment by naoe-tatara** [comment]
Thanks Annika for the text and sorry for a late response!
I think the criteria look great. Regarding @lexnederbragt 's comment:

> > and/or contributes to Carpentry@UiO’s GitHub repositories
> 
> How realistic is this? Has this ever happened?

I imagine that people who co-taught may have created a repository to make a workshop website, but otherwise, something like comments on issues in /organizational  or /studyGroup?

**Comment by arockenberger** [comment]
Hei @lexnederbragt, hei @naoe-tatara –

Thanks for your questions!

You are right: thinking about this again I get the same impression that this might actually not be very likely. However, as Naoe pointed out, those who are active in the StudyGroup have been a bit more involved in the GitHub maintenance. We have, for example, been working on making the website better and fixing some coding issues. I would count that as a contribution, but it might very well be counted among other contributions to the community, like participating in the StudyGroup.

I think we can remove the sentence.

Are there any other questions/comments?

**Comment by naoe-tatara** [comment]
No other comments from my side :)

**Comment by arockenberger** [comment]
I see there is no further need for discussion of this Issue at this point in time, so I will close the Issue. I have edited the document according to what Lex proposed.
If there are things you would like to change/edit/remove/add, please create a pull-request or feel free to re-open the Issue!
