### ISSUE TITLE
Meeting w/ instructor base - fall 2020

### ISSUE THREAD

**Issue by arockenberger** [uio-carpentry/organisational#76]
We are having trouble finding instructors/helpers for our on-site workshops as well as potential online-workshops.

We are therefore planning a 90min meeting with our instructor and helper community to discuss challenges, problems, and positive experiences with teaching during COVID-19, online/on-site/hybrid, etc.

Date: September 2020

We also want to create an opportunity for socializing.

Add a preliminary agenda and setup for the meeting by commenting on this issue.

**Comment by lexnederbragt** [comment]
I'd appreciate it if someone else than me could take the initiative here...

**Comment by naoe-tatara** [comment]
@arockenberger , I have had many different things going in parallel and have not totally caught up here, but is it something in-person? Together with re-sign up of organizer mailing list, shall we try a short survey? Probably there we could include question about listing names in the alumni list etc. as well? I will be back to here with some ideas later.

**Comment by arockenberger** [comment]
I was thinking of an online event, a bit like the Social Meetup we did during CarpentryCon@Home. I don't think we will reach enough people with a physical meeting and finding a room might be difficult, too.

I would like to send out the call for a meeting before we do the re-sign for the organizers' list, in case we are losing people.

AGENDA draft:

1. Welcome - How is everyone doing?
2. Share experiences teaching workshops during COVID-19
3. What can we do to support you teaching online or on-site?
  - Carpentries' recommendations for teaching online workshops
4. Social event: hang-out, chat

I consider running the meetup using Discord, because it allows audio/video, chat, and moving between "rooms" without the breakout-room hassle. It should be ok if we are doing it as a community, not as a UiO-thing.

**Comment by karinlag** [comment]
I'm very pro such a gathering. Maybe it would help if it could be done in the afternoon? Maybe 3pm on a Thursday? I know I wanted to join the meeting last week, but got blocked due to other things that ate up the time. Also, we can encourage people to bring a beverage to encourage socializing.

**Comment by naoe-tatara** [comment]
3 pm on a Thursday sounds good, I think. Probably we can leave an option for a collaborative note so that people can write their opinion about online teaching or share their experiences and expectations? It seems that the plan for a R workshop on the 17th Sep. is now on halt, we could eventually have it on the 17th? Or 10th is probably OK (i.e., not too short notice?)

**Comment by arockenberger** [comment]
Ok, the 17th would work for me, I have a lecture on 18th at 10.00 but it should be fine!
I'll send a call to the organizers list later today.

Should I try with Discord? https://discord.com/ it makes talking/video/rooms/hanging out a bit more social, but it is not UiO-approved like Zoom.

**Comment by lexnederbragt** [comment]
Good plans. I may not be able to join on the 17th before 16:00 or even later. We have started a Carpentry@UiO MS Teams already, UiO approved and all. I hear Discord is a popular alternative. I have no strong opinions, but sticking to one platform for the coming couple of years would be best...

**Comment by arockenberger** [comment]
The problem with Teams is, that it doesn't work for those outside of UiO but are still part of our community.
I've seen Discord being used for non-work communities, like study groups, interest groups, etc. especially during COVID when physical meeting was not an option.
But again: I am open for suggestions!

**Comment by karinlag** [comment]
Hi all! 

I have and am using Teams with people outside my organization. 

Can someone add me to the uio team with my Gmail address? Then we can test it out. 

Karin
--
karin.lagesen@gmail.com
________________________________

**Comment by naoe-tatara** [comment]
@karinlag , I added your gmail to Carpentry@UiO team on UiO Teams. Did you get an invitation?

**Comment by naoe-tatara** [comment]
I sent an invitation now :)

**Comment by arockenberger** [comment]
We have sent out invitations for a social meeting on Sep 17, 15:00-16:30 to the organizers mailing list.
Closing the Issue!
